language: node_js
node_js:
  - 'node'
  - '12'
  - 'lts/*'

matrix:
  allow_failures:
    - node_js: 'node'

services:
  - docker
cache:
  yarn: true
  directories:
    - $HOME/.cache

env:
  - NPM_TAG=`if [[ $TRAVIS_TAG =~ alpha|beta|rc ]]; then echo "next"; else echo "latest"; fi`

before_install:
  - docker run -d --rm -p 8554:8554 steabert/gst-rtsp-launch
script:
  - yarn test
  - yarn build
  - node rtsp-ws-server/tcp-ws-proxy.js >& tcp-ws-proxy.log &
  - yarn http-server examples/browser >& http-server.log &
  - yarn cypress run
deploy:
  - provider: releases
    file:
      - CHANGELOG.md
      - dist/media-stream-library.min.js
    api_key:
      secure: MGxt16mMu4Lf+aTVbGC1laBH84u5xv8xZ24iPhrYVKbYeEyuFxV/MWI3KSFkR99dulgCJ8/IMaB3HFmWMiCg1+ngl/0i8LSq05WrlKmto0hEJvbnaxJ63a9F25L2/+VRmqXVFf6qHHu1dG15xRWFFEvJTQ+c4MKaq/zacrbRBdtcuWCnRPwfzLxJXc57eM7XV3FgQECPdABuHugmF/m26L/t55+WbQdrPYAU9jBgZeJwNs2Fdxouhhl9VV4Po/fAxdzprXGLJe8zdz7WWWIdhiF7j9xQUhueBhaXDKLnPNEIBNIJXPnc6QwPwn0MnWWwgvCdQf0d5lmLWS156RW1JrWk0/XA9l+HmUPQ4BV7s2xHHaN3Vloz1Ya9WD3IofOC+lR1HFcwc8Zkz4O8EzaojFTRmvgwkM0vXudDb/CfQmVNUqNa69RC4GTo2RykA8tjUrVFnHxL4mqp299B7K0ALKs37VyuyyO8Vm1AHrp7VKfg37yQccUF2ZZUfsMdY70HwhMLehm34HrFXFspWbeO8fMMFjAAu0GLkt6FHWfn87/yJs1NfzIB5BsQutpGwh8wu/zFqT9wNjbQV7SBQwTXv/w68zTTxmlX8lTS658Bkl3x5+qFoZ17T9l9/ZGe9/AusUp948FmCLZLXBu/FFanhXxCXfRbz0lq+ocwrwmoMwE=
    skip_cleanup: true
    on:
      tags: true
      repo: AxisCommunications/media-stream-library-js
      node: '12'
  - provider: npm
    email: stevenv@axis.com
    tag: $NPM_TAG
    api_key:
      secure: D3qrZAW0kMoCpCjCThX1oIg8v0B+Bf2Ab7bX7drJjARaa6JUL3euFu103H9R2zJNBT9BrwtLeX/cS5fSgwg4i7pVkY+eb4a+7T+TeQuB1epXcGHOIhqfWbz3FKqyg3B4mXTSOdh1ptsrQh7S9XVLqgpHGgs2nVzVQnMUuzI8+AjZlSRcVslaT4Tc+FZa6802e7k4ig14zykVN3hwgeqr5qysnQ0Wf9cfJC+PUE+oNvJDieZE/C8CWHHXCUsngTLJ5mPpj9+MdabC+sgOsoe9kKKragAwGaX6PZ59RRsBC2G9WCjI3Cz72M+0eDsPd3/cJ2aNyZHId4ABPZHd35O6bJERxj3I9V+yPBz933aQ25waZ/iKPQdNrlxwfniO2m/xVqQaUovWH7Y5uiarZFFUpbnogMfrLarRsBUXmqi/mdUS/0jlCOp/TXe15uiCsWm6t9vn0phF0zY5xM/VoeFFcu1hLxhy3AyHtZltGVhCCtzBcwv3RANQmNmqA1DY6mXE0dskeIaGfB1UjefOSjTSGYvPau+xePYya8SR5nSUTthDUTxYROflYTdr7cyQAEDof+gwrvtq0idtGGsPOnzRsrGed3EkgBn1pkYOpyw4SCP2GhqQRuAJ1m0OHA1KVsc0fVMWCgn+9jlB+Hhpb6W/64JScfXuuB7M3MYLX4AKUm8=
    skip_cleanup: true
    on:
      tags: true
      repo: AxisCommunications/media-stream-library-js
      node: '12'
